// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('webAPIKey', defaultValue: ''),
    appId: '1:267571751143:web:1372c4b8e1b6a8121a9a42',
    messagingSenderId: '267571751143',
    projectId: 'ubs-dei-app-f87e2',
    authDomain: 'ubs-dei-app-f87e2.firebaseapp.com',
    storageBucket: 'ubs-dei-app-f87e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('androidAPIKey', defaultValue: ''),
    appId: '1:267571751143:android:72909824b7cdbf371a9a42',
    messagingSenderId: '267571751143',
    projectId: 'ubs-dei-app-f87e2',
    storageBucket: 'ubs-dei-app-f87e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('iosAPIKey', defaultValue: ''),
    appId: '1:267571751143:ios:8d6ebc1a6566d1181a9a42',
    messagingSenderId: '267571751143',
    projectId: 'ubs-dei-app-f87e2',
    storageBucket: 'ubs-dei-app-f87e2.appspot.com',
    iosBundleId: 'com.example.ubsDeiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('macosAPIKey', defaultValue: ''),
    appId: '1:267571751143:ios:8d6ebc1a6566d1181a9a42',
    messagingSenderId: '267571751143',
    projectId: 'ubs-dei-app-f87e2',
    storageBucket: 'ubs-dei-app-f87e2.appspot.com',
    iosBundleId: 'com.example.ubsDeiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('windowsAPIKey', defaultValue: ''),
    appId: '1:267571751143:web:ff72ddc3c9a0cf351a9a42',
    messagingSenderId: '267571751143',
    projectId: 'ubs-dei-app-f87e2',
    authDomain: 'ubs-dei-app-f87e2.firebaseapp.com',
    storageBucket: 'ubs-dei-app-f87e2.appspot.com',
  );
}
